package sushiservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-26T00:27:09.698-04:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "SushiService", 
                  wsdlLocation = "classpath:counter_sushi4_0.wsdl",
                  targetNamespace = "SushiService") 
public class SushiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("SushiService", "SushiService");
    public final static QName SushiServicePort = new QName("SushiService", "SushiServicePort");
    static {
        URL url = SushiService.class.getClassLoader().getResource("counter_sushi4_0.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SushiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:counter_sushi4_0.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public SushiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SushiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SushiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SushiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SushiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SushiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SushiServiceInterface
     */
    @WebEndpoint(name = "SushiServicePort")
    public SushiServiceInterface getSushiServicePort() {
        return super.getPort(SushiServicePort, SushiServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SushiServiceInterface
     */
    @WebEndpoint(name = "SushiServicePort")
    public SushiServiceInterface getSushiServicePort(WebServiceFeature... features) {
        return super.getPort(SushiServicePort, SushiServiceInterface.class, features);
    }

}
